title: Montier Kess
email: montier.kess@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Montier Kess – Developer and consultant that creates digital platforms, systems and business processes for modern brands.
baseurl: /
url: /

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-github-metadata

collections:
  selected-projects:
    output: true
    permalink: /projects/:title/
  content-series:
    output: false

instagram: https://www.instagram.com/montierkess.co
linkedin: https://www.linkedin.com/in/mkess
company: https://www.svncrwns.com
resume: https://www.dropbox.com/s/gigeljd1e9t246l/2019%20-%20Resume%20-%20Montier%20Kess%20-%20Atlanta.pdf?dl=0

encoding: utf-8